Repository Stokalas/D.Bilo-Siuntos, pull requests merged in 2022-03, with the labels that each got.

#2 Feature/ps-8, ps-9 setup react project
  dbilo-siuntos-frontend/.env
  dbilo-siuntos-frontend/.eslintrc.js
  dbilo-siuntos-frontend/.gitignore
  dbilo-siuntos-frontend/.husky/pre-commit
  dbilo-siuntos-frontend/.husky/pre-push
  dbilo-siuntos-frontend/.lintstagedrc
  dbilo-siuntos-frontend/.nvmrc
  dbilo-siuntos-frontend/.prettierrc
  dbilo-siuntos-frontend/.stylelintrc
  dbilo-siuntos-frontend/README.md
  dbilo-siuntos-frontend/package.json
  dbilo-siuntos-frontend/public/.htaccess
  dbilo-siuntos-frontend/public/favicon.ico
  dbilo-siuntos-frontend/public/index.html
  dbilo-siuntos-frontend/public/logo192.png
  dbilo-siuntos-frontend/public/logo512.png
  dbilo-siuntos-frontend/public/manifest.json
  dbilo-siuntos-frontend/public/robots.txt
  dbilo-siuntos-frontend/src/App.tsx
  dbilo-siuntos-frontend/src/RootComponent.tsx
  dbilo-siuntos-frontend/src/components/DateDisplay.tsx
  dbilo-siuntos-frontend/src/index.tsx
  dbilo-siuntos-frontend/src/pages/HomePage.tsx
  dbilo-siuntos-frontend/src/pages/NotFoundPage.tsx
  dbilo-siuntos-frontend/src/react-app-env.d.ts
  dbilo-siuntos-frontend/src/resources/api-constants.ts
  dbilo-siuntos-frontend/src/resources/routes-constants.ts
  dbilo-siuntos-frontend/src/serviceWorker.ts
  dbilo-siuntos-frontend/src/setupTests.ts
  dbilo-siuntos-frontend/src/store/actions/data.ts
  dbilo-siuntos-frontend/src/store/reducers/data.ts
  dbilo-siuntos-frontend/src/store/reducers/store.ts
  dbilo-siuntos-frontend/src/styles/_mixins.sass
  dbilo-siuntos-frontend/src/styles/_variables.sass
  dbilo-siuntos-frontend/src/styles/main.sass
  dbilo-siuntos-frontend/src/tests/components/DateDisplay.test.tsx
  dbilo-siuntos-frontend/src/tests/pages/HomePage.test.tsx
  dbilo-siuntos-frontend/src/tests/pages/NotFoundPage.test.tsx
  dbilo-siuntos-frontend/src/types/reducers.ts
  dbilo-siuntos-frontend/src/utility/customAxios.ts
  dbilo-siuntos-frontend/src/utility/functions.ts
  dbilo-siuntos-frontend/tsconfig.json
  dbilo-siuntos-frontend/yarn.lock
Labels: Front-end

#3 PS-24 CI pipeline for backend
  .github/workflows/ci.yaml
  WebAPI.Tests/MockTests.cs
  WebAPI.Tests/WebAPI.Tests.csproj
  WebAPI/WebAPI.sln
Labels: Back-end

#4 Feature/ps 10 setup database
  Infrastructure/DatabaseContext.cs
  Infrastructure/Infrastructure.csproj
  Infrastructure/Migrations/20220328152318_InitialMigration.Designer.cs
  Infrastructure/Migrations/20220328152318_InitialMigration.cs
  Infrastructure/Migrations/DatabaseContextModelSnapshot.cs
  Infrastructure/Models/Parcel.cs
  WebAPI/Program.cs
  WebAPI/WebAPI.csproj
  WebAPI/WebAPI.sln
  WebAPI/appsettings.json
Labels: SQL
