Repository Stokalas/D.Bilo-Siuntos, pull requests merged in 2022-04, with the labels that each got.

#7 PS-22 Readme for DB setup and made migrations run on WebAPI startup
  WebAPI/Program.cs
  WebAPI/readme.md
Labels: Back-end, SQL

#9 PS-20 Mock post endpoint parcel
  README.md
  WebAPI/Controllers/ParcelController.cs
  WebAPI/Controllers/WeatherForecastController.cs
Labels: Back-end

#10 PS-44 Create single parcel endpoint
  WebAPI/Controllers/ParcelController.cs
Labels: Back-end

#11 PS-40 File logger
  WebAPI/Program.cs
  WebAPI/WebAPI.csproj
Labels: Back-end

#16 PS-49 Renamed tasks inside CI file
  .github/workflows/ci.yaml
Labels: Infrastructure

#17 PS-65 updated page title and favicon
  dbilo-siuntos-frontend/public/favicon.ico
  dbilo-siuntos-frontend/public/index.html
  dbilo-siuntos-frontend/public/logo192.png
  dbilo-siuntos-frontend/public/logo512.png
Labels: Front-end

#18 PS-55 Register new parcel page/form
  dbilo-siuntos-frontend/package.json
  dbilo-siuntos-frontend/src/components/router/Header.tsx
  dbilo-siuntos-frontend/src/components/router/Router.tsx
  dbilo-siuntos-frontend/src/pages/SendParcelPage/SendParcel.tsx
  dbilo-siuntos-frontend/src/pages/SendParcelPage/SendParcelForm.tsx
  dbilo-siuntos-frontend/src/resources/routes-constants.ts
  dbilo-siuntos-frontend/yarn.lock
Labels: Front-end
